### ISSUE TITLE
Motivating example 

### ISSUE THREAD

**Issue by zitterbewegung** [jsmaniac/typed-worklist#1]
Can you give a motivating example of why someone would use this in the documentation .

**Comment by SuzanneSoy** [comment]
Hello,

Sorry for the late reply, I added some documentation on the same day you opened the issue, but forgot to reply here.

http://docs.racket-lang.org/typed-worklist/ now explains the main use case for this package (processing heterogeneous graphs, with multiple waiting queues for nodes of different types that have to be processed).

I'm closing this now, feel free to re-open if you need any clarification!
